<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Invoice_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get invoice by id
     */
    function get_invoice($id)
    {
        return $this->db->get_where('invoice',array('id'=>$id))->row_array();
    }

    function login($params)
    {
        return $this->db->get_where('invoice',$params)->row_array();
    }
        
    /*
     * Get all invoice
     */
    function get_all_invoice()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('invoice')->result_array();
    }
    function get_all_vehicle()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('vehicle')->result_array();
    }
     function get_all_servive_type()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('servive_type')->result_array();
    }
    function get_all_invoice2()
    {
        $this->db->order_by('id', 'desc');
        $this->db->where('assigned_status',NOT_ASSIGNED);
        return $this->db->get('invoice')->result_array();
    }
        function invoice_count()
    {
        $this->db->from('invoice');
        return $this->db->count_all_results();
    }   
        
    /*
     * function to add new invoice
     */
    function add_invoice($params)
    {
        $this->db->insert('invoice',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update invoice
     */
    function update_invoice($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('invoice',$params);
    }
     function update_invoice2($id,$params)
    {
        $this->db->where('invoice',$id);
        return $this->db->update('invoice',$params);
    }
    
    /*
     * function to delete invoice
     */
    function delete_invoice($id)
    {
        return $this->db->delete('invoice',array('id'=>$id));
    }
}
