<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Services_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get services by id
     */
    function get_services($id)
    {
        return $this->db->get_where('services',array('id'=>$id))->row_array();
    }

    function login($params)
    {
        return $this->db->get_where('services',$params)->row_array();
    }
        
    /*
     * Get all services
     */
    function get_all_services()
    {
         $this->db->order_by('id', 'desc');
        return $this->db->get('services')->result_array();
    }
    function get_all_services2($id)
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('services')->result_array();

        //  $this->db->select('services.*,vehicle.name as vehicle_name,users.first_name as driver_name,service_type.name as service_type_name');
        // $this->db->from('services');
        // $this->db->join('vehicle','services.vehicle_id=vehicle.id','left outer');
        // $this->db->join('users','services.driver_id=users.id','left outer');
        // $this->db->join('service_type','services.service_type=service_type.id','left outer');
        // $this->db->where('services.id',$id);
        // return $this->db->get()->row_array();
    }
    function get_all_vehicle()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('vehicle')->result_array();
    }
     function get_all_service_type()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('service_type')->result_array();
    }
    // function get_all_services2()
    // {
    //     $this->db->order_by('id', 'desc');
    //     $this->db->where('assigned_status',NOT_ASSIGNED);
    //     return $this->db->get('services')->result_array();
    // }
        function services_count()
    {
        $this->db->from('services');
        return $this->db->count_all_results();
    }   
        
    /*
     * function to add new services
     */
    function add_services($params)
    {
        $this->db->insert('services',$params);
        return $this->db->insert_id();
    }
      function add_services2($params)
    {
        $this->db->insert('services2',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update services
     */
    function update_services($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('services',$params);
    }
     function update_services2($id,$params)
    {
        $this->db->where('services',$id);
        return $this->db->update('services',$params);
    }
    
    /*
     * function to delete services
     */
    function delete_services($id)
    {
        return $this->db->delete('services',array('id'=>$id));
    }
}
