<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Ticket_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get inspection by id
     */
  
      function get_ticket($id)
    {
        return $this->db->get_where('tickets',array('id'=>$id))->row_array();
    }

  
   
      function tickets_count()
    {
        $this->db->from('tickets');
        return $this->db->count_all_results();
    }   
    /*
     * Get all inspection
     */
  
      function get_all_tickets($params = array())
    {
        $this->db->order_by('id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('tickets')->result_array();
    }

  

    function get_inspection_export()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('inspection')->result_array();
    }
        
    /*
     * function to add new inspection
     */
   
      function add_ticket($params)
    {
        $this->db->insert('tickets',$params);
        return $this->db->insert_id();
    }

    function add_excel($params)
    {
        $this->db->insert_batch('inspection',$params);
        return $this->db->insert_id();
    }
    /*
     * function to update inspection
     */
    
     function update_tickets($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('tickets',$params);
    }
    /*
     * function to delete inspection
     */
   
    function delete_ticket($id)
    {
        return $this->db->delete('tickets',array('id'=>$id));
    }
}
