#include <iostream>
#include <fstream>

int main()
{
  std::ofstream f;
  f.open("test.plan");

  f << "{\n";
  f << "    \"fileType\": \"Plan\",\n";
  f << "    \"geoFence\": {\n";
  f << "        \"circles\": [\n";
  f << "        ],\n";
  f << "        \"polygons\": [\n";
  f << "        ],\n";
  f << "        \"version\": 2\n";
  f << "    },\n";
  f << "    \"groundStation\": \"QGroundControl\",\n";
  f << "    \"mission\": {\n";
  f << "        \"cruiseSpeed\": 15,\n";
  f << "        \"firmwareType\": 12,\n";
  f << "        \"globalPlanAltitudeMode\": 1,\n";
  f << "        \"hoverSpeed\": 5,\n";
  f << "        \"items\": [\n";
  f << "            {\n";
  f << "                \"AMSLAltAboveTerrain\": null,\n";
  f << "                \"Altitude\": 50,\n";
  f << "                \"AltitudeMode\": 1,\n";
  f << "                \"autoContinue\": true,\n";
  f << "                \"command\": 22,\n";
  f << "                \"doJumpId\": 1,\n";
  f << "                \"frame\": 3,\n";
  f << "                \"params\": [\n";
  f << "                    15,\n";
  f << "                    0,\n";
  f << "                    0,\n";
  f << "                    null,\n";
  f << "                    37.08573377,\n";
  f << "                    -76.37887271,\n";
  f << "                    50\n";
  f << "                ],\n";
  f << "                \"type\": \"SimpleItem\"\n";
  f << "            },\n";
  f << "            {\n";
  f << "                \"AMSLAltAboveTerrain\": null,\n";
  f << "                \"Altitude\": 50,\n";
  f << "                \"AltitudeMode\": 1,\n";
  f << "                \"autoContinue\": true,\n";
  f << "                \"command\": 16,\n";
  f << "                \"doJumpId\": 2,\n";
  f << "                \"frame\": 3,\n";
  f << "                \"params\": [\n";
  f << "                    0,\n";
  f << "                    0,\n";
  f << "                    0,\n";
  f << "                    null,\n";
  f << "                    37.08681892,\n";
  f << "                    -76.37668146,\n";
  f << "                    50\n";
  f << "                ],\n";
  f << "                \"type\": \"SimpleItem\"\n";
  f << "            },\n";
  f << "            {\n";
  f << "                \"AMSLAltAboveTerrain\": null,\n";
  f << "                \"Altitude\": 50,\n";
  f << "                \"AltitudeMode\": 1,\n";
  f << "                \"autoContinue\": true,\n";
  f << "                \"command\": 16,\n";
  f << "                \"doJumpId\": 3,\n";
  f << "                \"frame\": 3,\n";
  f << "                \"params\": [\n";
  f << "                    0,\n";
  f << "                    0,\n";
  f << "                    0,\n";
  f << "                    null,\n";
  f << "                    37.08559138,\n";
  f << "                    -76.37562277,\n";
  f << "                    50\n";
  f << "                ],\n";
  f << "                \"type\": \"SimpleItem\"\n";
  f << "            },\n";
  f << "            {\n";
  f << "                \"AMSLAltAboveTerrain\": null,\n";
  f << "                \"Altitude\": 50,\n";
  f << "                \"AltitudeMode\": 1,\n";
  f << "                \"autoContinue\": true,\n";
  f << "                \"command\": 16,\n";
  f << "                \"doJumpId\": 4,\n";
  f << "                \"frame\": 3,\n";
  f << "                \"params\": [\n";
  f << "                    0,\n";
  f << "                    0,\n";
  f << "                    0,\n";
  f << "                    null,\n";
  f << "                    37.08447675,\n";
  f << "                    -76.37772785,\n";
  f << "                    50\n";
  f << "                ],\n";
  f << "                \"type\": \"SimpleItem\"\n";
  f << "            },\n";
  f << "            {\n";
  f << "                \"AMSLAltAboveTerrain\": null,\n";
  f << "                \"Altitude\": 50,\n";
  f << "                \"AltitudeMode\": 1,\n";
  f << "                \"autoContinue\": true,\n";
  f << "                \"command\": 16,\n";
  f << "                \"doJumpId\": 5,\n";
  f << "                \"frame\": 3,\n";
  f << "                \"params\": [\n";
  f << "                    0,\n";
  f << "                    0,\n";
  f << "                    0,\n";
  f << "                    null,\n";
  f << "                    37.0855079,\n";
  f << "                    -76.3786819,\n";
  f << "                    50\n";
  f << "                ],\n";
  f << "                \"type\": \"SimpleItem\"\n";
  f << "            },\n";
  f << "            {\n";
  f << "                \"autoContinue\": true,\n";
  f << "                \"command\": 20,\n";
  f << "                \"doJumpId\": 6,\n";
  f << "                \"frame\": 2,\n";
  f << "                \"params\": [\n";
  f << "                    0,\n";
  f << "                    0,\n";
  f << "                    0,\n";
  f << "                    0,\n";
  f << "                    0,\n";
  f << "                    0,\n";
  f << "                    0\n";
  f << "                ],\n";
  f << "                \"type\": \"SimpleItem\"\n";
  f << "            }\n";
  f << "        ],\n";
  f << "        \"plannedHomePosition\": [\n";
  f << "            37.08573377,\n";
  f << "            -76.37887271,\n";
  f << "            7.137364280395303\n";
  f << "        ],\n";
  f << "        \"vehicleType\": 2,\n";
  f << "        \"version\": 2\n";
  f << "    },\n";
  f << "    \"rallyPoints\": {\n";
  f << "        \"points\": [\n";
  f << "        ],\n";
  f << "        \"version\": 2\n";
  f << "    },\n";
  f << "    \"version\": 1\n";
  f << "}\n";

  return 0;
}
