<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
 
class Forms extends Admin_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Forms_model');
        $this->load->model('Items_model');
    } 

    /*
     * Listing of forms
     */
    function index()
    {
        $data['forms'] = $this->Forms_model->get_all_forms2();
        
        $data['_view'] = 'forms/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new forms
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('name','Patient Name','required');
	
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'title' => $this->input->post('title'),
				'name' => $this->input->post('name'),
				'surname' => $this->input->post('surname'),
				'lab_sub_no' => $this->input->post('lab_sub_no'),
				'gender' => $this->input->post('gender'),
				'tel' => $this->input->post('tel'),
				'email' => $this->input->post('email'),
				'address' => $this->input->post('address'),
				'passport_no' => $this->input->post('passport_no'),
				'dob' => $this->input->post('dob'),
				'time_swab_taken' => $this->input->post('time_swab_taken'),
                'date_swab_taken' => $this->input->post('date_swab_taken'),
				'created_by' => $this->session->userdata('first_name'),
            );

            $forms_id = $this->Forms_model->add_forms($params);
            redirect('forms/index');
        }
        else
        {            
            $data['_view'] = 'forms/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a forms
     */
    function edit($id)
    {   
        // check if the forms exists before trying to edit it
        $data['forms'] = $this->Forms_model->get_forms($id);
        $data['items'] = $this->Items_model->get_all_items();
        
        if(isset($data['forms']['id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('part_no','Part Number','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
				
				  'part_no' => $this->input->post('part_no'),
                'description' => $this->input->post('description'),
                'quantity' => $this->input->post('quantity'),
                'ppu' =>  $this->input->post('ppu'),
                'location' =>  $this->input->post('location'),
                );              
                $this->Forms_model->update_forms($id,$params);   
                redirect('forms/index');
            }
            else
            {
                $data['_view'] = 'forms/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The forms you are trying to edit does not exist.');
    } 





      function assign($id)
    {   
        // check if the forms exists before trying to edit it
        $data['assign'] = $this->Forms_model->get_forms($id);
         $data['test_identifiers'] = $this->Test_identifiers_model->get_all_test_identifiers2();

        
        if(isset($data['assign']['id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('name','Patient Name','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
				'lab_sub_no' => $this->input->post('lab_sub_no'),
				
                );
          $this->Forms_model->update_forms($id,$params); 
          $params2 = array(
				'assigned_status' => ASSIGNED,
				
                );  
                $test_identifiers_id = $this->input->post('lab_sub_no'); 
                $this->Test_identifiers_model->update_test_identifiers2($test_identifiers_id,$params2);redirect('forms/index');
            }
            else
            {
                $data['_view'] = 'forms/assign';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The forms you are trying to edit does not exist.');
    } 

      function results($id)
    {   
        // check if the forms exists before trying to edit it
        $data['forms'] = $this->Forms_model->get_forms2($id);
        
        if(isset($data['forms']['id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('name','Patient Name','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
				'title' => $this->input->post('title'),
				'name' => $this->input->post('name'),
				'surname' => $this->input->post('surname'),
				'lab_sub_no' => $this->input->post('lab_sub_no'),
				'gender' => $this->input->post('gender'),
				'tel' => $this->input->post('tel'),
				'email' => $this->input->post('email'),
				'address' => $this->input->post('address'),
				'passport_no' => $this->input->post('passport_no'),
				'dob' => $this->input->post('dob'),
				// 'relevant_info' => $this->input->post('relevant_info'),
				// 'case_define' => '',
				// 'specimen_info' => '',
				'created_by' => $this->session->userdata('first_name'),
                );
                 
              
                $this->Forms_model->update_forms($id,$params);            
                redirect('forms/index');
            }
            else
            {
                $data['_view'] = 'forms/results';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The forms you are trying to edit does not exist.');
    } 



    /*
     * Deleting forms
     */
    function remove($id)
    {
        $forms = $this->Forms_model->get_forms($id);

        // check if the forms exists before trying to delete it
        if(isset($forms['id']))
        {
            $this->Forms_model->delete_forms($id);
            redirect('forms/index');
        }
        else
            show_error('The forms you are trying to delete does not exist.');
    }
    
}
