<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class View_request extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Services_model');
        $this->load->model('User_model');
        $this->load->model('Invoice_model');
    } 

   
    function results($id)
    {
        $data['services'] = $this->Services_model->get_all_services2($id);
     // echo "<pre>";   print_r($data['services']); exit();
        $data['id'] = $id;
       
        $this->load->view('services/greeting_sign2',$data);
    }



       function update_status($id)
    {   
        // check if the services exists before trying to edit it
        $data['services'] = $this->Services_model->get_services($id);
        
        if(isset($data['services']['id']))
        {
            $this->load->library('form_validation');
 
                $params = array(
                'picked_status' => $this->input->post('status'),
                'modified_by' => $this->session->userdata('first_name'),
                );
              
                $this->Services_model->update_services($id,$params);            
                $this->load->view('success');

            }
        else
            show_error('The services you are trying to Update does not exist.');
    } 

   
    
}
